/*
 * ============================================================
 *  SMART HELMET — MINE SAFETY EDGE AI  |  SENDER (Laptop 1)
 *  ESP32 WROOM — Decision Tree Inference + AES-128 Encrypted LoRa
 * ============================================================
 *  Sensors : BMI160 (acc + gyro) | DHT11 (temp + humidity) | MQ135 (gas)
 *  Output  : Encrypted NORMAL / WARNING / EMERGENCY via LoRa
 *
 *  Encryption: AES-128-CBC using mbedTLS (built into ESP32 SDK)
 *              Key and IV must MATCH the RECEIVER exactly.
 *
 *  Required files in SAME folder:
 *    decision_tree_model.h   ← Auto-generated by train_decision_tree.py
 *
 *  Libraries (Arduino IDE > Tools > Manage Libraries):
 *    1. DFRobot_BMI160        by DFRobot
 *    2. DHT sensor library    by Adafruit
 *    3. Adafruit Unified Sensor by Adafruit  (DHT dependency)
 *    4. LoRa                  by Sandeep Mistry
 *    (mbedTLS is built-in to ESP32 — no extra install needed)
 *
 *  Wiring:
 *    BMI160  SDA → GPIO21  |  SCL → GPIO22   (I2C)
 *    DHT11   DATA → GPIO4  |  VCC → 3.3V
 *    MQ135   AOUT → GPIO34 |  VCC → 5V       (use ADC1 only!)
 *    LoRa    SCK→18  MISO→19  MOSI→23  NSS→5  RST→14  DIO0→2
 * ============================================================
 */

#include <Arduino.h>
#include "decision_tree_model.h"
#include "DFRobot_BMI160.h"
#include <DHT.h>
#include <Wire.h>
#include <SPI.h>
#include <LoRa.h>
#include <WiFi.h>
#include "mbedtls/aes.h"

// ─────────────────────────────────────────────────────────────
// PIN DEFINITIONS
// ─────────────────────────────────────────────────────────────
#define DHT_PIN        4
#define DHT_TYPE       DHT11
#define MQ135_PIN      34
#define LORA_SCK       18
#define LORA_MISO      19
#define LORA_MOSI      23
#define LORA_NSS       5
#define LORA_RST       14
#define LORA_DIO0      2
#define LORA_FREQ      433E6
#define BMI160_ADDR    0x68
#define WIFI_SSID      "Rupanshi's A35"
#define WIFI_PASSWORD  "Rupanshi123"

// ─────────────────────────────────────────────────────────────
// AES-128 ENCRYPTION KEY & IV
//  ⚠️  KEEP SECRET — Must match receiver exactly!
//  Change these 16-byte values to your own secret before deploying.
// ─────────────────────────────────────────────────────────────
static const uint8_t AES_KEY[16] = {
    0x4D, 0x69, 0x6E, 0x65, 0x53, 0x61, 0x66, 0x65,
    0x48, 0x65, 0x6C, 0x6D, 0x65, 0x74, 0x32, 0x34
};
// IV can be fixed or rotated; fixed is simpler for this use case
static const uint8_t AES_IV[16] = {
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
    0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10
};

// ─────────────────────────────────────────────────────────────
// TIMING CONFIG
// ─────────────────────────────────────────────────────────────
#define SAMPLE_INTERVAL_MS  5000
#define MQ135_WARMUP_MS     30000
#define LORA_EVERY_N        3

// ─────────────────────────────────────────────────────────────
// SENSOR OBJECTS & STATE
// ─────────────────────────────────────────────────────────────
DFRobot_BMI160 bmi160;
DHT            dht(DHT_PIN, DHT_TYPE);

bool          wifi_ok       = false;
bool          lora_ok       = false;
unsigned long last_sample_ms = 0;
int           inference_count = 0;
int           last_prediction = 1;

// ─────────────────────────────────────────────────────────────
// AES-128-CBC ENCRYPT
//  plaintext  → must be padded to multiple of 16 (PKCS#7)
//  Returns number of ciphertext bytes written into 'output'
// ─────────────────────────────────────────────────────────────
int aes_encrypt(const char* plaintext, uint8_t* output) {
    size_t pt_len = strlen(plaintext);

    // PKCS#7 padding
    size_t pad_len  = 16 - (pt_len % 16);
    size_t buf_len  = pt_len + pad_len;

    uint8_t padded[128] = {0};            // Max packet ~100 bytes
    memcpy(padded, plaintext, pt_len);
    for (size_t i = pt_len; i < buf_len; i++) padded[i] = (uint8_t)pad_len;

    // CBC needs a mutable IV copy
    uint8_t iv_copy[16];
    memcpy(iv_copy, AES_IV, 16);

    mbedtls_aes_context ctx;
    mbedtls_aes_init(&ctx);
    mbedtls_aes_setkey_enc(&ctx, AES_KEY, 128);
    mbedtls_aes_crypt_cbc(&ctx, MBEDTLS_AES_ENCRYPT, buf_len, iv_copy, padded, output);
    mbedtls_aes_free(&ctx);

    return (int)buf_len;
}

// ─────────────────────────────────────────────────────────────
// WiFi Connect
// ─────────────────────────────────────────────────────────────
void connectWiFi() {
    Serial.printf("\n[WIFI] Connecting to %s\n", WIFI_SSID);
    WiFi.mode(WIFI_STA);
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    unsigned long t = millis();
    while (WiFi.status() != WL_CONNECTED && millis() - t < 15000) {
        Serial.print(".");
        delay(500);
    }
    wifi_ok = (WiFi.status() == WL_CONNECTED);
    if (wifi_ok) {
        Serial.println("\n[WIFI] Connected! IP: " + WiFi.localIP().toString());
    } else {
        Serial.println("\n[WIFI] Failed. Running offline.");
    }
}

// ─────────────────────────────────────────────────────────────
// SETUP
// ─────────────────────────────────────────────────────────────
void setup() {
    Serial.begin(115200);
    delay(1000);
    connectWiFi();

    Serial.println("============================================");
    Serial.println("  SMART HELMET — SENDER  |  AES-128 LoRa");
    Serial.println("============================================");

    dht.begin();
    Serial.println("[INIT] DHT11 OK");

    Wire.begin();
    if (bmi160.softReset() != BMI160_OK) {
        Serial.println("[FATAL] BMI160 reset failed");
        while (true) delay(1000);
    }
    if (bmi160.I2cInit(BMI160_ADDR) != BMI160_OK) {
        Serial.println("[FATAL] BMI160 I2C init failed");
        while (true) delay(1000);
    }
    Serial.println("[INIT] BMI160 OK");

    analogReadResolution(12);
    analogSetAttenuation(ADC_11db);
    Serial.println("[INIT] MQ135 ADC OK");

    SPI.begin(LORA_SCK, LORA_MISO, LORA_MOSI, LORA_NSS);
    LoRa.setPins(LORA_NSS, LORA_RST, LORA_DIO0);
    if (!LoRa.begin(LORA_FREQ)) {
        Serial.println("[WARN] LoRa init failed — running without LoRa");
    } else {
        LoRa.setSpreadingFactor(10);
        LoRa.setSignalBandwidth(125E3);
        LoRa.setCodingRate4(5);
        LoRa.setTxPower(17);
        lora_ok = true;
        Serial.printf("[INIT] LoRa OK @ %.0f MHz\n", LORA_FREQ / 1E6);
    }

    Serial.println("[INIT] MQ135 warming up (30 seconds)...");
    for (int i = 30; i > 0; i--) {
        Serial.printf("       %2ds remaining...\r", i);
        delay(1000);
    }
    Serial.println("\n[INIT] MQ135 ready!");
    Serial.println("[INIT] AES-128-CBC encryption enabled");
    Serial.println("============================================\n");
}

// ─────────────────────────────────────────────────────────────
// MAIN LOOP
// ─────────────────────────────────────────────────────────────
void loop() {
    if (wifi_ok && WiFi.status() != WL_CONNECTED) {
        Serial.println("[WIFI] Lost connection. Reconnecting...");
        connectWiFi();
    }

    if (millis() - last_sample_ms < SAMPLE_INTERVAL_MS) return;
    last_sample_ms = millis();

    // ── 1. Read DHT11 ──────────────────────────────────────
    float temperature = dht.readTemperature();
    float humidity    = dht.readHumidity();
    if (isnan(temperature) || isnan(humidity)) {
        Serial.println("[WARN] DHT11 read failed — retrying next cycle");
        return;
    }

    // ── 2. Read MQ135 ──────────────────────────────────────
    long adc_sum = 0;
    for (int i = 0; i < 10; i++) { adc_sum += analogRead(MQ135_PIN); delay(2); }
    float adc_avg = adc_sum / 10.0f;
    float gas_ppm = constrain(350.0f + (adc_avg / 4095.0f) * (4095.0f - 350.0f), 350.0f, 4095.0f);

    // ── 3. Read BMI160 ─────────────────────────────────────
    int16_t bmi_data[6] = {0};
    if (bmi160.getAccelGyroData(bmi_data) != 0) {
        Serial.println("[WARN] BMI160 read failed — retrying next cycle");
        return;
    }
    float acc_x = bmi_data[3] / 16384.0f;
    float acc_y = bmi_data[4] / 16384.0f;
    float acc_z = bmi_data[5] / 16384.0f;
    float acc_r = sqrt(acc_x*acc_x + acc_y*acc_y + acc_z*acc_z);
    float gyr_x = (bmi_data[0] / 131.0f) * DEG_TO_RAD;
    float gyr_y = (bmi_data[1] / 131.0f) * DEG_TO_RAD;
    float gyr_z = (bmi_data[2] / 131.0f) * DEG_TO_RAD;
    float gyr_r = sqrt(gyr_x*gyr_x + gyr_y*gyr_y + gyr_z*gyr_z);

    // ── 4. Feature array ───────────────────────────────────
    float features[NUM_FEATURES] = {
        temperature, humidity, gas_ppm,
        acc_x, acc_y, acc_z, acc_r,
        gyr_x, gyr_y, gyr_z, gyr_r
    };

    // ── 5. Decision Tree ───────────────────────────────────
    int prediction = predict(features);
    prediction     = safety_override(features, prediction);
    const char* label = CLASS_LABELS[prediction];
    inference_count++;

    // ── 6. Serial output ───────────────────────────────────
    Serial.println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    Serial.printf( "  Inference #%d\n", inference_count);
    Serial.printf( "  Temp:%.0fC  Hum:%.0f%%  Gas:%.1fppm\n", temperature, humidity, gas_ppm);
    Serial.printf( "  Acc:%.3fG  Gyro:%.1fdps\n", acc_r, gyr_r);
    Serial.printf( "  RESULT: %s\n", label);
    Serial.println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

    // ── 7. LoRa Transmission (Encrypted) ───────────────────
    if (!lora_ok) return;

    bool is_emergency  = (prediction == 0);
    bool state_changed = (prediction != last_prediction);
    bool periodic_send = (inference_count % LORA_EVERY_N == 0);

    if (is_emergency || state_changed || periodic_send) {

        // Build plaintext CSV packet
        char packet[96];
        snprintf(packet, sizeof(packet), "%s,%d,%d,%d,%.3f,%.1f",
                 label,
                 (int)temperature, (int)humidity, (int)gas_ppm,
                 acc_r, gyr_r);

        // Encrypt
        uint8_t ciphertext[128] = {0};
        int cipher_len = aes_encrypt(packet, ciphertext);

        // Send raw bytes over LoRa
        LoRa.beginPacket();
        LoRa.write(ciphertext, cipher_len);
        LoRa.endPacket();

        Serial.printf("[LoRa] Plaintext : %s\n", packet);
        Serial.printf("[LoRa] Encrypted : %d bytes sent\n\n", cipher_len);
    }

    last_prediction = prediction;
}
